# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 08:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name of Organizer')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Website Address')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('0', 'Unknown'), ('1', 'Conference'), ('2', 'Meeting'), ('3', 'Banquet'), ('4', 'Seminar'), ('5', 'Conclave'), ('6', 'Workshop'), ('7', 'Convention'), ('8', 'Symposium')], default=0, max_length=1)),
                ('venue', models.CharField(blank=True, max_length=256)),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date Started')),
                ('end_date', models.DateField(default=datetime.datetime(2017, 2, 18, 8, 35, 42, 177114, tzinfo=utc), verbose_name='Date Ended')),
                ('level', models.CharField(choices=[('0', 'unknown'), ('1', 'institutional'), ('2', 'local'), ('3', 'national'), ('4', 'international')], default=0, max_length=1)),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Research Title')),
                ('research_type', models.CharField(choices=[('0', 'unknown'), ('1', 'study'), ('2', 'project')], default=0, max_length=1, verbose_name='Type of Research')),
                ('presentation_type', models.CharField(choices=[('0', 'unknown'), ('1', 'oral'), ('2', 'poster')], default=0, max_length=1, verbose_name='Type of Presentation')),
                ('other_info', models.TextField(blank=True, null=True)),
                ('authors', models.ManyToManyField(blank=True, to='employees.Employee', verbose_name='List of authors')),
                ('organizers', models.ManyToManyField(to='events.Organizer', verbose_name='List of Organizers')),
                ('presentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presentor', to='employees.Employee', verbose_name='Presented by')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name_plural': 'Research Presentations',
            },
        ),
    ]
