# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 09:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentation',
            options={'ordering': ('research_title',), 'verbose_name_plural': 'Research Presentations'},
        ),
        migrations.AddField(
            model_name='presentation',
            name='research_title',
            field=models.CharField(default='Unknown Research', help_text='Enter the Research Title', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presentation',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 2, 18, 9, 5, 8, 607454, tzinfo=utc), verbose_name='Date Ended'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='title',
            field=models.CharField(help_text='Enter the Event/Conference/Symposium name here', max_length=256),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='type',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'Conference'), ('2', 'Meeting'), ('3', 'Banquet'), ('4', 'Seminar'), ('5', 'Conclave'), ('6', 'Workshop'), ('7', 'Convention'), ('8', 'Symposium')], default=0, help_text='What Type of Event is this?', max_length=1),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='venue',
            field=models.CharField(blank=True, help_text='Where did this happen (City,Province, Place)', max_length=256),
        ),
    ]
