# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 04:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfDiscipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g allied medicine, engineering, science etc.', max_length=64)),
                ('remarks', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Name of Campus')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='Location of Campus')),
                ('contact_no', models.CharField(blank=True, help_text='Follow this format e.g 02-433-0262', max_length=30)),
                ('info', models.TextField(blank=True, help_text='Describe what information about the Campus', max_length=256)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director', to=settings.AUTH_USER_MODEL, verbose_name='Campus Director')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Campuses',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Add a Designation', max_length=50)),
                ('contact_no', models.CharField(blank=True, help_text='Follow this format e.g 02-433-0262', max_length=30)),
                ('info', models.TextField(blank=True, help_text='Describe what is about this Department', max_length=256)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departmenthead', to=settings.AUTH_USER_MODEL, verbose_name='Chairman/Head of the Department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('employee_no', models.PositiveIntegerField(blank=True, help_text='Your Employee Number', null=True, unique=True)),
                ('gender', models.CharField(choices=[('0', 'unknown'), ('1', 'male'), ('2', 'female')], default=0, max_length=1)),
                ('civil_status', models.CharField(choices=[('0', 'unknown'), ('1', 'single'), ('2', 'married'), ('3', 'widowed/widower')], default=0, max_length=1)),
                ('address', models.TextField(blank=True, max_length=256)),
                ('birth_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('institution', models.CharField(choices=[('0', 'Unknown'), ('1', 'PSU')], default=1, help_text='Choose/Add Institution you belong to', max_length=1)),
                ('work_status', models.CharField(choices=[('0', 'Unknown'), ('1', 'JO'), ('2', 'Regular'), ('3', 'COS')], default=0, help_text='Status of Appointment', max_length=1)),
                ('designation', models.CharField(blank=True, help_text='e.g Chairman, Director, etc', max_length=255)),
                ('started', models.DateField(auto_now_add=True, help_text='Started working in the Institution', null=True)),
                ('mobile_no', models.CharField(blank=True, help_text='Follow this format e.g +639399581237', max_length=30)),
                ('landline_no', models.CharField(blank=True, help_text='Follow this format e.g 02-433-0262', max_length=30)),
                ('department', models.ForeignKey(blank=True, help_text='For Faculty Only', null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('expertise', models.CharField(help_text='Separate expertise with comma..', max_length=255)),
                ('area_of_discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area', to='employees.AreaOfDiscipline')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Expertise',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Add new rank here', max_length=50)),
                ('info', models.TextField(blank=True, help_text='Information about this Rank', max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name of Unit')),
                ('division', models.CharField(choices=[('0', 'Unknown'), ('1', 'Academic Affairs'), ('2', 'Research & Extension'), ('3', 'Administration')], default=0, help_text='Choose Division', max_length=1)),
                ('contact_no', models.CharField(blank=True, help_text='Follow this format e.g 02-433-0262', max_length=30)),
                ('info', models.TextField(blank=True, help_text='Describe what is about this Designation', max_length=256)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus', to='employees.Campus', verbose_name='Campus')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unithead', to=settings.AUTH_USER_MODEL, verbose_name='Head of Unit')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='expertise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Expertise'),
        ),
        migrations.AddField(
            model_name='employee',
            name='rank',
            field=models.ForeignKey(blank=True, help_text='Choose Staff/Faculty Rank', null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Rank'),
        ),
        migrations.AddField(
            model_name='employee',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Choose the Unit user is currently working', null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Unit'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='unit',
            field=models.ForeignKey(help_text='Choose which Unit/Collegee this Department belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='employees.Unit'),
        ),
    ]
