# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.ForeignKey(blank=True, help_text='Add your educational Attainment here', null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Attainment'),
        ),
    ]
