# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 04:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attainment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('undergrad',),
            },
        ),
        migrations.CreateModel(
            name='Doctoral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('degree', models.CharField(default='None', help_text='Enter PhD title here', max_length=128, unique=True)),
                ('units', models.PositiveIntegerField(blank=True, null=True)),
                ('year_graduated', models.PositiveIntegerField(blank=True, null=True)),
                ('school', models.CharField(blank=True, help_text='School', max_length=128)),
                ('remarks', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ('degree',),
            },
        ),
        migrations.CreateModel(
            name='Masteral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ini', models.CharField(default='None', help_text='e.g MSIT, MBA, MIS etc', max_length=32)),
                ('degree', models.CharField(default='None', help_text='Enter Masters title here', max_length=128)),
                ('units', models.PositiveIntegerField(blank=True, null=True)),
                ('year_graduated', models.PositiveIntegerField(blank=True, null=True)),
                ('school', models.CharField(blank=True, help_text='School', max_length=128)),
                ('remarks', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ('degree',),
            },
        ),
        migrations.CreateModel(
            name='Undergrad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ini', models.CharField(default='None', help_text='e.g BSIT, BSECE, BSBA etc', max_length=32)),
                ('degree', models.CharField(default='None', help_text='Enter Undergrad course here', max_length=128)),
                ('units', models.PositiveIntegerField(blank=True, null=True)),
                ('year_graduated', models.PositiveIntegerField(blank=True, null=True)),
                ('school', models.CharField(blank=True, help_text='School', max_length=128)),
                ('remarks', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ('degree',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='undergrad',
            unique_together=set([('ini', 'degree')]),
        ),
        migrations.AlterUniqueTogether(
            name='masteral',
            unique_together=set([('ini', 'degree')]),
        ),
        migrations.AddField(
            model_name='attainment',
            name='doctorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Doctoral', verbose_name='Doctoral Degrees'),
        ),
        migrations.AddField(
            model_name='attainment',
            name='masteral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Masteral', verbose_name='Masteral Degrees'),
        ),
        migrations.AddField(
            model_name='attainment',
            name='undergrad',
            field=models.ForeignKey(blank=True, help_text='Choose only 1 if (multi course)', null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Undergrad', verbose_name='Undergrad Degrees'),
        ),
        migrations.AddField(
            model_name='attainment',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
