# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title of Article', max_length=256)),
                ('start_page', models.PositiveIntegerField(blank=True, help_text='Start page in the publication')),
                ('end_page', models.PositiveIntegerField(blank=True, help_text='End page in the publication')),
                ('keywords', models.CharField(blank=True, help_text='Enter keywords here', max_length=256)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='ArticleAuthors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('authorship', models.IntegerField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Article')),
            ],
            options={
                'ordering': ('authorship',),
            },
        ),
        migrations.CreateModel(
            name='ArticleDiscipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('info', models.CharField(help_text='Info', max_length=50)),
                ('article', models.ForeignKey(help_text='Choose the article', on_delete=django.db.models.deletion.CASCADE, to='publications.Article')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('info', models.TextField(blank=True, help_text='Add info here', max_length=256)),
                ('articles', models.ManyToManyField(related_name='articles', through='publications.ArticleAuthors', to='publications.Article')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='employees.Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Add discipline here i.e Marketing, InfoTech, Engineering ', max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('type', models.CharField(choices=[('0', 'zero'), ('1', 'one'), ('2', 'two'), ('3', 'three')], help_text='Types of Publication', max_length=1)),
                ('issn', models.CharField(blank=True, help_text='Enter the 8 Digit ISSN Number of the publication', max_length=8)),
                ('vol_num', models.PositiveIntegerField(blank=True)),
                ('issue_num', models.PositiveIntegerField(blank=True)),
                ('date_published', models.DateField(blank=True, help_text='Date Published (make sure year is accurate)')),
                ('doi', models.CharField(blank=True, help_text='Enter the DOI of the publication', max_length=60)),
                ('editor', models.ForeignKey(help_text='Choose the editor, or leave blank if unknown', null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='articlediscipline',
            name='discipline',
            field=models.ForeignKey(help_text='Choose Discipline', on_delete=django.db.models.deletion.CASCADE, to='publications.Discipline'),
        ),
        migrations.AddField(
            model_name='articleauthors',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='disciplines',
            field=models.ManyToManyField(related_name='discipline', through='publications.ArticleDiscipline', to='publications.Discipline'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='publications.Publication'),
        ),
    ]
